### ISSUE TITLE
Use hoodie from node.js

### ISSUE THREAD

**Issue by billymoon** [hoodiehq/hoodie-cli#165]
Is it possible to use hoodie from a node.js client? I want to do something like...

    var Hoodie = require("hoodie");
    var hoodie = new Hoodie({serverUrl: "http://localhost:6001"});
    hoodie.account.signIn('anyone', 'anywhere');
    hoodie.store.findAll('todo').then(function(allTodos) {
        allTodos.forEach(function(todo){ console.log(todo); });
    });

**Comment by janl** [comment]
that’s not quite possible at the moment, I think (cc @gr2m), but I like the looks of this, wanna help make it happen? :)

**Comment by gr2m** [comment]
Yeah, this is not possible. Our thoughts are:

1. On server side, you need different APIs than in the browsers. Most of the APIs are authenticated as admin and are cross account
2. The server API should have callbacks instead of returning promises, as this is the dominant convention in Node.js land.

Could you explain your use case(s) to have the same `hoodie` API on the server as the one you have in the browser?

**Comment by svnlto** [comment]
I haven't tried this myself but I'd imagine this "could possibly" work if you pull in `jsdom` or something.

**Comment by boennemann** [comment]
Closing in favor of https://github.com/hoodiehq/hoodie.js/issues/299
